#pragma once

// ===== BUFFER SIZES =====
#define SERIALX_INPUT_BUFFER_SIZE 64
#define SERIALX_ACCESS_KEY_SIZE 32
#define SERIALX_VAR_NAME_SIZE 20

// ===== BASE TYPES =====
#define SERIALX_SUPPORT_BOOL 1
#define SERIALX_SUPPORT_INT 1
#define SERIALX_SUPPORT_FLOAT 1
#define SERIALX_SUPPORT_STRING 1

// ===== EXTENDED TYPES =====
#define SERIALX_SUPPORT_CHAR 1
#define SERIALX_SUPPORT_CHARSTRING 1 // char[64]; buffer
#define SERIALX_SUPPORT_UINT8 1
#define SERIALX_SUPPORT_UINT16 1
#define SERIALX_SUPPORT_UINT32 1
#define SERIALX_SUPPORT_LONG 1
#define SERIALX_SUPPORT_DOUBLE 1
#define SERIALX_DOUBLE_PRECISION 6

// ===== OPTIONAL FEATURES =====
#define SERIALX_SHOW_VALUES_IN_HELP 0 // Not implemented yet
#define SERIALX_ENABLE_BATCH_CMD 0
#define SERIALX_ENABLE_JSON_OUTPUT 0
#define SERIALX_ENABLE_EEPROM 0
#define SERIALX_ENABLE_TIMESTAMP 0

// ===== OPTIMIZATION FLAGS =====
#define SERIALX_ENABLE_AUTH 1
